name: My First Workflow
#on trigger, on push(any push). can add conditions
on: 
  push:
jobs: 
  echo_the_date:
    runs-on: ubuntu-latest
    steps: 
    - name: echo the date
      run: echo "The current time and date is $(date)"
    - name: echo the current branch
      run: echo ${{ github.ref_name }}
      # $ {{}} github action. compiler reads this syntax and replaces it to github branch name. this is a github action 
    # failures will cause subsequent steps to fail/not do
  test_and_deploy:
    runs-on: ubuntu-latest
    env: 
      OPENWEATHERMAP_KEY: ${{ secrets.openweathermap_api }} #word in double brackets is refering to secrets in github. not case-sensitive. 
      #OPENWEATHERMAP_KEY is the name where its referenced in the code. 
      #is done as set key=value in console. before maven bootstrap is called to run the server. 

    steps: 
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
    #https://github.com/marketplace/actions/setup-maven
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.3
      with:
        maven-version: 3.8.5    

    - name: Checkout the source
      uses: actions/checkout@v3
    
    - name: Run test
      run: mvn clean test

    #https://github.com/marketplace/actions/deploy-to-heroku
    - name: Deploy to Heroku 
      uses: actions/checkout@v2
      uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_KEY}}
        heroku_app_name: ${{HEROKU_APP_NAME}} 
        heroku_email: "${{secrets.EMAIL}}
        branch: ${{ github.ref_name }} 



# - <<< array. dash and space
# indentation is object!

#https://github.com/cheongliyuan/WeatherAppTest/settings/secrets/actions
#where to add secrets 
#tell github where to find our secrets. (from echo jobs)