name: My First Workflow
#on trigger, on push(any push). can add conditions
on: 
  push:
jobs: 
  echo_the_date:
    runs-on: ubuntu-latest
    steps: 
    - name: echo the date
      run: echo "The current time and date is $(date)"
    - name: Simulate a fail
      run: exit 1
    - name: echo the current branch
      run: echo ${{ github.ref_name }}
      # $ {{}} github action. compiler reads this syntax and replaces it to github branch name. this is a github action 


    # failures will cause subsequent steps to fail/not do



# - <<< array. dash and space
# indentation is object!