name: My First Workflow
#on trigger, on push(any push). can add conditions
on: 
  push:
jobs: 
  echo_the_date:
    runs-on: ubuntu-latest
    steps: 
    - name: echo the date
      run: echo "The current time and date is $(date)"
    - name: echo the current branch
      run: echo ${{ github.ref_name }}
      # $ {{}} github action. compiler reads this syntax and replaces it to github branch name. this is a github action 
    # failures will cause subsequent steps to fail/not do
  test_and_deploy:
    runs-on: ubuntu-latest
    steps: 
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
    #https://github.com/marketplace/actions/setup-maven
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.3
      with:
        maven-version: 3.8.5    

    - name: Checkout the source
      uses: actions/checkout@v3
    
    - name: Run test
      run: mvn clean test



# - <<< array. dash and space
# indentation is object!